name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Terraform Init
      run: terraform init -input=false
      
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      
    - name: Terraform Apply
      run: terraform apply -input=false tfplan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  # Example of using secrets for sensitive data

    - name: Terraform Output
      run: terraform output  # Optionally, display Terraform outputs
