# nginx-deployment-with-secret.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
          subPath: custom-nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
          items:
          - key: custom-nginx.conf
            path: custom-nginx.conf
