name: Terraform1

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./.github/workflows

- name: Terraform Plan
  run: terraform plan
  working-directory: ./.github/workflows

- name: Terraform Apply
  run: terraform apply --auto-approve
  working-directory: ./.github/workflows
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set Terraform Output Variables
        id: terraform_output
        run: |
          echo "PRIVATE_IP=$(terraform output private_ip)" >> $GITHUB_ENV
          echo "PUBLIC_IP=$(terraform output public_ip)" >> $GITHUB_ENV
        working-directory: ./.github/workflows

      - name: Use Terraform Outputs
        run: |
          echo "Private IP: $PRIVATE_IP"
          echo "Public IP: $PUBLIC_IP"
        working-directory: ./.github/workflows
